# Description: This file contains the configuration for the Bullhorn tasks.
# Each task specifies the endpoint, fields, query, count, start, rename_map, and transform_map.
#
from utils import timestamp_to_date, clean_html, extract_skill_names

hubspot_tasks = {
    "companies": {
        "properties": [
            "name",
            "hubspot_owner_id",
            "type",
            "industry",
            "state",
            "city",
            "numberofemployees",
            "description",
            "linkedin_company_page",
            "hs_merged_object_ids",
            "bh_company_id",
            "lifecyclestage",
            "hs_is_target_account",
        ],
    },
    "contacts": {
        "properties": [
            "hubspot_owner_id",
            "bh_contact_id",
            "bh_company_id",
            "lifecyclestage",
            "notes_last_contacted",
            "hs_latest_source",
            "num_conversion_events",
            "hs_analytics_source",
            "hubspotscore",
            "lastmodifieddate",
            "email",
            "jobtitle",
            "num_contacted_notes",
            "hs_sa_first_engagement_object_type",
            "company",
        ]
    },
    "deals": {
        "properties": [
            "dealname",
            "hubspot_owner_id",
            "deal_owner_string",
            "associatedCompanyIds",
            "csd_owner",
            "notes_last_contacted",
            "dealtype",
            "createdate",
            "closedate",
            "hs_manual_forecast_category",
            "customer_hourly_rate",
            "consultant_hourly_rate",
            "number_of_hours",
            "next_step_history",
            "revenue_solution",
            "revenue_source",
            "bh_company_id",
            "bh_contact_id",
            "bh_job_id",
            "bh_placement_id",
            "deal_score",
            "required_skills",
            "amount",
            "projected_hours___week",
            "pipeline",
            "dealstage",
            "number_of_hours",
            "start_date",
            "end_date",
            "acquisition_deal_id",
            "hs_is_closed_won",
        ]
    },
}

bullhorn_tasks = {
    "submissions": {
        "endpoint": "JobSubmission",
        "fields": "id,dateAdded,jobOrder,candidate,status,source,payRate,billRate,salary,comments",
        "query": "dateAdded>1000000000000",
        "count": 500,
        "start": 0,
        "rename_map": {
            "id": "bh_submission_id",
            "dateAdded": "submission_created_date",
            "status": "status",
            "source": "source",
            "payRate": "pay_rate",
            "billRate": "bill_rate",
            "salary": "salary",
            "comments": "comments",
            "jobOrder.id": "bh_job_id",
            "jobOrder.title": "job_name",
            "candidate.id": "bh_candidate_id",
            "candidate.firstName": "candidate_first_name",
            "candidate.lastName": "candidate_last_name",
        },
        "transform_map": {
            "id": str,
            "dateAdded": lambda x: timestamp_to_date(x).isoformat(),
            "status": str,
            "source": str,
            "payRate": str,
            "billRate": str,
            "salary": str,
            "comments": str,
            "jobOrder.id": str,
            "jobOrder.title": str,
            "candidate.id": str,
            "candidate.firstName": str,
            "candidate.lastName": str,
        },
    },
    "candidates": {
        "endpoint": "Candidate",
        "fields": "id,dateAdded,firstName,lastName,customInt1,status,occupation,"
        "companyName,willRelocate,phone,email,certifications,dateAvailable,customText12,"
        "customText10,customText21,travelLimit,customText11,employeeType",
        "query": "dateAdded:[1000000000000 TO *]",
        "count": 500,
        "start": 0,
        "rename_map": {
            "id": "bh_candidate_id",
            "dateAdded": "candidate_created_date",
            "firstName": "first_name",
            "lastName": "last_name",
            "customInt1": "years_experience",
            "status": "status",
            "occupation": "occupation",
            "companyName": "company_name",
            "willRelocate": "will_relocate",
            "phone": "phone",
            "email": "email",
            "certifications": "certifications",
            "dateAvailable": "date_available",
            "customText12": "hs_contact_id",
            "customText10": "hs_deal_id",
            "customText21": "hs_company_id",
            "travelLimit": "travel_limit",
            "customText11": "custom_text_11",
            "employeeType": "employee_type",
        },
        "transform_map": {
            "id": str,
            "dateAdded": lambda x: timestamp_to_date(x).isoformat(),
            "firstName": str,
            "lastName": str,
            "customInt1": str,
            "status": str,
            "occupation": str,
            "companyName": str,
            "willRelocate": bool,
            "phone": str,
            "email": str,
            "certifications": str,
            "dateAvailable": lambda x: (
                timestamp_to_date(x).isoformat()
                if timestamp_to_date(x) is not None
                else None
            ),
            "customText12": str,
            "customText10": str,
            "customText21": str,
            "travelLimit": int,
            "customText11": str,
            "employeeType": str,
            "_score": float,
        },
    },
    "companies": {
        "endpoint": "ClientCorporation",
        "fields": "id,dateAdded,customText10,name,status,companyURL,ownership,address",
        "query": "dateAdded>1000000000000",
        "count": 500,
        "start": 0,
        "rename_map": {
            "id": "bh_company_id",
            "dateAdded": "company_created_date",
            "customText10": "hs_company_id",
            "name": "company_name",
            "status": "status",
            "companyURL": "company_url",
            "ownership": "ownership",
            "address.address1": "address_1",
            "address.address2": "address_2",
            "address.city": "address_city",
            "address.countryCode": "address_country_code",
            "address.countryID": "address_country_id",
            "address.countryName": "address_country_name",
            "address.state": "address_state",
            "address.timezone": "address_timezone",
            "address.zip": "address_zip",
        },
        "transform_map": {
            "id": str,
            "dateAdded": lambda x: timestamp_to_date(x).isoformat(),
            "customText10": str,
            "name": str,
            "status": str,
            "companyURL": str,
            "ownership": str,
            "address.address1": str,
            "address.address2": str,
            "address.city": str,
            "address.countryCode": str,
            "address.countryID": str,
            "address.countryName": str,
            "address.state": str,
            "address.timezone": str,
            "address.zip": str,
        },
    },
    "placements": {
        "endpoint": "Placement",
        "fields": "id,dateAdded,clientCorporation,jobOrder,jobSubmission,"
        "candidate,status,dateBegin,dateEnd,payRate,clientBillRate,salaryUnit,dateEffective, hoursPerDay",
        "query": "dateAdded>1000000000000",
        "count": 500,
        "start": 0,
        "rename_map": {
            "id": "bh_placement_id",
            "dateAdded": "placement_created_date",
            "clientCorporation.id": "bh_company_id",
            "clientCorporation.name": "company_name",
            "jobOrder.id": "bh_job_id",
            "jobOrder.title": "job_name",
            "status": "status",
            "jobSubmission.id": "bh_submission_id",
            "jobSubmission": "job_submission",
            "candidate.id": "bh_candidate_id",
            "candidate.firstName": "first_name",
            "candidate.lastName": "last_name",
            "dateBegin": "start_date",
            "dateEnd": "end_date",
            "clientBillRate": "client_bill_rate",
            "payRate": "pay_rate",
            "salaryUnit": "salary_unit",
            "dateEffective": "date_effective",
            "hoursPerDay": "hours_per_day",
        },
        "transform_map": {
            "id": str,
            "dateAdded": lambda x: timestamp_to_date(x).isoformat(),
            "clientCorporation.id": str,
            "clientCorporation.name": str,
            "jobOrder.id": str,
            "jobOrder.title": str,
            "status": str,
            "jobSubmission.id": str,
            "jobSubmission": str,
            "candidate.id": str,
            "candidate.firstName": str,
            "candidate.lastName": str,
            "dateBegin": lambda x: (
                timestamp_to_date(x).isoformat()
                if timestamp_to_date(x) is not None
                else None
            ),
            "dateEnd": lambda x: (
                timestamp_to_date(x).isoformat()
                if timestamp_to_date(x) is not None
                else None
            ),
            "clientBillRate": float,
            "payRate": float,
            "salaryUnit": str,
            "dateEffective": lambda x: (
                timestamp_to_date(x).isoformat()
                if timestamp_to_date(x) is not None
                else None
            ),
            "hoursPerDay": float,
        },
    },
    "contacts": {
        "endpoint": "ClientContact",
        "fields": "id,dateAdded,clientCorporation,firstName,lastName,"
        "occupation,phone,email,status,customText10",
        "query": "dateAdded>1000000000000",
        "count": 500,
        "start": 0,
        "rename_map": {
            "id": "bh_contact_id",
            "dateAdded": "contact_created_date",
            "clientCorporation.id": "bh_company_id",
            "firstName": "first_name",
            "lastName": "last_name",
            "occupation": "occupation",
            "phone": "phone",
            "email": "email",
            "status": "status",
            "customText10": "hs_deal_id",
        },
        "transform_map": {
            "id": str,
            "dateAdded": lambda x: timestamp_to_date(x).isoformat(),
            "clientCorporation.id": str,
            "clientCorporation.name": str,
            "firstName": str,
            "lastName": str,
            "occupation": str,
            "phone": str,
            "email": str,
            "status": str,
            "customText10": str,
        },
    },
    "jobs": {
        "endpoint": "JobOrder",
        "fields": "id,dateAdded,status,clientCorporation,title,description,isOpen,reasonClosed,"
        "numOpenings,employmentType,type,clientContact,owner,durationWeeks,"
        "startDate,dateEnd,hoursOfOperation,customText4,customText5,customText1,"
        "travelRequirements,payRate,clientBillRate,skills,skillList, customText10",
        "query": "dateAdded>1000000000000",
        "count": 500,
        "start": 0,
        "rename_map": {
            "id": "bh_job_id",
            "dateAdded": "job_created_date",
            "clientCorporation.id": "bh_company_id",
            "clientContact.id": "bh_contact_id",
            "clientCorporation.name": "company_name",
            "clientContact.firstName": "contact_first_name",
            "clientContact.lastName": "contact_last_name",
            "owner.id": "owner_id",
            "owner.firstName": "owner_first_name",
            "owner.lastName": "owner_last_name",
            "customText10": "hs_deal_id",
            "status": "status",
            "skills.total": "skills_total",
            "skills.data": "skills_values",
            "title": "title",
            "description": "description",
            "isOpen": "is_open",
            "reasonClosed": "reason_closed",
            "numOpenings": "num_openings",
            "employmentType": "employment_type",
            "type": "type",
            "durationWeeks": "duration_weeks",
            "startDate": "start_date",
            "dateEnd": "end_date",
            "hoursOfOperation": "hours_of_operation",
            "customText4": "projected_hours_week",
            "customText5": "upside",
            "customText1": "contract_rate_range",
            "travelRequirements": "travel_requirements",
            "clientBillRate": "client_bill_rate",
            "payRate": "pay_rate",
            "customText10": "hs_deal_id",
        },
        "transform_map": {
            "id": str,
            "dateAdded": lambda x: timestamp_to_date(x).isoformat(),
            "clientCorporation.id": str,
            "clientCorporation.name": str,
            "clientContact.id": str,
            "clientContact.firstName": str,
            "clientContact.lastName": str,
            "owner.id": str,
            "owner.firstName": str,
            "owner.lastName": str,
            "status": str,
            "title": str,
            "description": clean_html,
            "isOpen": bool,
            "reasonClosed": str,
            "numOpenings": int,
            "employmentType": str,
            "type": str,
            "startDate": lambda x: (
                timestamp_to_date(x).isoformat()
                if timestamp_to_date(x) is not None
                else None
            ),
            "dateEnd": lambda x: (
                timestamp_to_date(x).isoformat()
                if timestamp_to_date(x) is not None
                else None
            ),
            "durationWeeks": str,
            "hoursOfOperation": str,
            "customText4": str,
            "customText5": str,
            "customText1": str,
            "travelRequirements": str,
            "payRate": float,
            "clientBillRate": float,
            "customText10": str,
            "skills.data": extract_skill_names,
        },
    },
}
