name: ETL Workflow

on:
  push:
    branches: [main]


jobs: 
    bullhorn:
        name: Bullhorn ETL
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: read
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            - name: Google Auth
              id: auth
              uses: google-github-actions/auth@v2.1.3
              with:
                workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
                service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
                create_credentials_file: true
                access_token_lifetime: '300s'
            - name: Run Bullhorn ETL
              env:
                GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
                BH_CLIENT_ID: ${{ secrets.BH_CLIENT_ID }}
                BH_CLIENT_SECRET: ${{ secrets.BH_CLIENT_SECRET }}
                BH_USERNAME: ${{ secrets.BH_USERNAME }}
                BH_PASSWORD: ${{ secrets.BH_PASSWORD }}
                BH_CORP_TOKEN: ${{ secrets.BH_CORP_TOKEN }}

              run: |
                    python ./src/etl/bullhorn_etl.py

    hubspot:
        name: Hubspot ETL
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: read
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            - name: Google Auth
              id: auth
              uses: google-github-actions/auth@v2.1.3
              with:
                workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
                service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
                create_credentials_file: true
                access_token_lifetime: '300s'
            - name: Run Hubspot ETL
              env:
                GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
                HUBSPOT_TOKEN: ${{ secrets.HUBSPOT_TOKEN }}

              run: |
                    python ./src/etl/hubspot_etl.py
